version: '3.8'

services:
  sotehus-power:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sotehus-power
    ports:
      - "8080:8080"
    environment:
      # Add your environment variables here
      # You can also use .env file
      - PYTHONUNBUFFERED=1
    env_file:
      - .env  # Optional: if you have a .env file with configuration
    volumes:
      # Mount code for development (comment out for production)
      - .:/app
    restart: unless-stopped
    networks:
      - sotehus-network

networks:
  sotehus-network:
    driver: bridge
